### ISSUE TITLE
Beta release and Ionic 3.x -- update your sass.config.js

### ISSUE THREAD

**Issue by mwiley63** [GerritErpenstein/ionic2-custom-icons#17]
Versions:
  * Ionic 3.0.1
  * app-scripts 1.3.0
  * ionic2-custom-icons 0.4.1-beta.2

I am confused on the instructions for the beta release.  When I do a fresh install with `@beta` and run ionic build, I get the following error:
```
sass: node_modules/ionic2-custom-icons/directive/scss/ionic2-custom-icons.scss, line: 1 
      Please update your sass.config.js. See the changelog for instructions: 
      https://github.com/GerritErpenstein/ionic2-custom-icons/blob/master/CHANGELOG.md 
       L1:  @error "Please update your sass.config.js. See the changelog for instructions: https://github.com/GerritErpe
```
However, the linked changelog was last updated on Nov. 1 2016 and the beta README links to the stable release's README for configuration.

Is the configuration different for the beta release?

**Comment by GerritErpenstein** [comment]
Hi Matthew!
Indeed it is a bit confusing right now as the configuration has slightly changed. Sorry for that!
In your `sass.config.js` make sure to use the new path:
```
node_modules/ionic2-custom-icons/ionic/scss/
```
(instead of `node_modules/ionic2-custom-icons/directive/scss/`)

It is correctly stated in the [docs/CONFIGURATION.md](docs/CONFIGURATION.md) but I should have made it more obvious. As the beta does not seem to have any bugs, I will make a stable release the next few days and add clear update instructions to the CHANGELOG file.

I will keep the issue open in case other people stumble upon this error.

Thanks for opening the issue!

**Comment by mwiley63** [comment]
Thank you!  I missed that small change 👍

**Comment by GerritErpenstein** [comment]
The CHANGELOG has been updated with upgrade instructions.
