### ISSUE TITLE
rebuild and prewatch scripts not working Ionic 2 RC2/RC3

### ISSUE THREAD

**Issue by marteb** [GerritErpenstein/ionic2-custom-icons#6]
i’m not sure what causes this problem, but running only `ionic serve` doesn’t trigger the prebuild and prewatch scripts, which results in errors like `copy: Error copying "/Users/name/project/.tmp-custom-icons/fonts" to "/Users/name/project/www/assets/fonts": File not found` and `sass: stdin, line: 1 File to import not found or unreadable: .tmp-custom-icons/scss/variables.scss Parent style sheet: stdin`

When first doing the `npm run prewatch` step by hand, it works.

**Comment by GerritErpenstein** [comment]
Hi @marteb, thank you for the report! I will take a look at it at the weekend and provide a fix. It's probably just a minor issue.

**Comment by GerritErpenstein** [comment]
Luckily the fix was trivial. Just update the `scripts` section in your `package.json` as described in the README: [1.1 Add npm-scripts](https://github.com/GerritErpenstein/ionic2-custom-icons#11-add-npm-scripts)
**Side note:** When updating `@ionic/app-scripts`, always make sure to also check/update your `copy.config.js` and `sass.config.js`.
